version: '3.4'

services:
  web:
    image: ${DOCKER_REGISTRY-}web
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    environment: 
    - ASPNETCORE_ENVIRONMENT=Docker
    networks:
    - dbnetwork
    depends_on:
    - db

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: P@ssw0rd!
    networks:
     - dbnetwork

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: P@ssw0rd!
    networks:
     - dbnetwork

  db:
    image: luizcarlosfaria/mssql-server-linux
    environment:
     - 'ACCEPT_EULA=Y'
     - 'MSSQL_PID=Express'
     - 'SA_PASSWORD=8k3W2C2BVzAW9p'
     - 'MSSQL_DATABASE=dbPdv'
     - 'MSSQL_DATABASE_COLLATE=SQL_Latin1_General_CP1_CI_AI'
     - 'MSSQL_USER=meuUsuario'
     - 'MSSQL_PASSWORD=minhaSenha'
    ports:
    - 1433:1433
    networks:
    - dbnetwork

networks:
 dbnetwork:
  driver: bridge
